name: Build & Release

on:
  release:
    types: [ published ]
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  build-native:
    name: GraalVM on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest ]
        include:
          - os: ubuntu-latest
            platform: 'linux-amd64'
          - os: 'macos-latest'
          - platform: 'darwin-arm64'
          - os: 'macos-13'
            platform: 'darwin-amd64'

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '25'
          distribution: 'liberica'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Version
        shell: bash
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout 2>&1 | grep -v "WARNING" | tail -n1)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build Native Images
        shell: bash
        run: |
          mvn -B package --file pom.xml -DskipTests

      - name: Rename artifact by OS (non windows)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          mv target/algorithms-* target/${{ matrix.output }}${{ matrix.ext }}

      - name: Upload non windows images to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/${{ matrix.output }}${{ matrix.ext }}
          asset_name: ${{ matrix.output }}${{ matrix.ext }}
          tag: ${{ env.VERSION }}
          overwrite: true
          make_latest: true