name: Build & Release

on:
  release:
    types: [ created ]
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  build-native:
    name: GraalVM on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
        include:
          - os: ubuntu-latest
            output: sorting-algorithm-visualization-linux
            ext: ''
          - os: macos-latest
            output: sorting-algorithm-visualization-macos
            ext: ''
          - os: windows-latest
            output: sorting-algorithm-visualization-windows
            ext: .exe

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '25'
          distribution: 'liberica'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout 2>&1 | grep -v "WARNING" | tail -n1)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build Native Images
        shell: bash
        run: |
          mvn -B package --file pom.xml -DskipTests

      - name: Upload images to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "target/algorithms-*"
          tag: ${{ env.VERSION }}
          overwrite: true
          make_latest: true