name: Build & Release

on:
  release:
    types: [ published ]
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  build-native:
    name: GraalVM on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
        include:
          - os: ubuntu-latest
            output: sorting-algorithm-visualization-linux
            ext: ''
          - os: macos-latest
            output: sorting-algorithm-visualization-macos
            ext: ''
          - os: windows-latest
            output: sorting-algorithm-visualization-windows
            ext: .exe

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '25'
          distribution: 'liberica'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Version
        shell: bash
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout 2>&1 | grep -v "WARNING" | tail -n1)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build Native Images
        shell: bash
        run: |
          mvn -B package --file pom.xml -DskipTests

      - name: Rename artifact by OS (non windows)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          mv target/algorithms-* target/${{ matrix.output }}${{ matrix.ext }}

      - name: Rename artifact by OS (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          $file = Get-ChildItem "target\algorithms-*" | Select-Object -First 1
          $dest = Join-Path "target" "sorting-algorithm-visualization-windows.exe"
          Rename-Item $file.FullName $dest

      - name: Upload Windows artifact
        if: runner.os == 'Windows'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/sorting-algorithm-visualization-windows.exe
          asset_name: sorting-algorithm-visualization-windows.exe
          tag: ${{ github.event.release.tag_name }}
          overwrite: true
          make_latest: true

      - name: Upload non windows images to release
        if: runner.os != 'Windows'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/${{ matrix.output }}${{ matrix.ext }}
          asset_name: ${{ matrix.output }}${{ matrix.ext }}
          tag: ${{ env.VERSION }}
          overwrite: true
          make_latest: true